#-----------------------------------------------------------------------------------------------------------#
#TESTING.
# Added some examples for proteins just to see that it works. These are some scenarios we could add in the DashBoard.
# Also added the system.time just to show how slow the function is.

# We will assume that the function takes the sequences in this type of format! (important with the newline).
seq1 <- ">random sequence 1 consisting of 20 residues.
KMMIDIHWGMWWYEYMMCLD"

seq2 <- ">random sequence 1 consisting of 20 residues.
DVYRVCQNVFRYHHFCKRTI"

system.time(statSignf(seq1, seq2))

seq1 <- ">non-random sequence 1 very similar to 2.
KKKKKKKKKKRRRRNNRRLLLMMMNM"

seq2 <- ">non-random sequence 2 very similar to 1.
KKKKKKKKKKKRRRRRRLLLLMMMNN"

system.time(statSignf(seq1, seq2, num.shuffles = 5000))

seq1 <- ">random sequence 1 consisting of 500 residues.
YWWCSKEWDHFPDVTTCTPSEQYPAWAMHNMILPNWQLAEMMQSYRYIPNIALPNHQLTK
AHSMWAQHSMYVQRCCETKDLLFNDDTSQDKAYPFKQMESNHHITNEFPNKCKILTSVKH
ATLWNLQALGCCKDPCRSNKFHKKLNIDIHCSPGWTGWNAQYSSPGPFCWEPKTVNYSWF
RFKWHYFPCVHNIGSSRQCVWLRYFHLSSEQWKQGARGWVVVIFGACSGWYPWDNGQLYQ
EKNIFCAGKGQCATDQYFNYLWSWMISAGWAVYPYDECVTRTVISLFEVAYYFRHPYMWH
NITIMLRNETLPAVTQCVLETLHTHYCLALWLEEMYPCTDEGYNRKTPGDTHVQDCAFFS
ESHKHDVKTNWVGSDSINYNPGSVMWKICDHLGAGMYGRPTPADWSQSIITNHICCGDAS
HCGEQWCAVNNDSVSTMISQFQTSEWAHPIVINQHGIEPDMSWGELARVLTQNPGLGQQN
TIRMKTFYRKFFPCMYFNFQ"

seq2 <- ">random sequence 1 consisting of 500 residues.
FWMLVNRLCQDTGWEYADCRPDHGNESRMMYKDCFYHITDPAEATVFPIESFCQHLCSNF
WSNTHWRIINYPPLHWKNYCGSAFWGRNYGEWSCFEDRMPFATEIETHSNPVFNDFQEAQ
CNNQARKKNGWKVSAPQEAMPQGMMRLTWIFIHEMWGWFSWVWRLIQNQINEPGVKPLEL
CSETQHGVFGWRDIAIMIRMEYKCDVLFMWLILCPCYYSDQFCKRIAAHQEAMRWKIAKT
AWQFVGKIKGPKCRMLTERRQFACEVTEQACKRCLPHAVRHTGQSHKYHCTAFRPFTKIS
VAYGVEIGESFFFQWYWQFRFSFATAWAISNWGQGWSLCIEEVNWNDIKEHFTFTTKIML
VFTENFTEHSQEIFDSLMDHGPDHKVSIIARQMVACQIWITHKMGCCHDGLLYTPTHDWF
LQVRVPCFFQWVEGWNGIEDDIPGHVRMNSMTSWLNKPLASRILLDIYIMTWDNRWFKWD
KTWMVVGHNIHDAWSFENVK"

system.time(statSignf(seq1, seq2, num.shuffles = 5000))
system.time(statSignf(seq1, seq2, num.shuffles = 5000, subst.matrix = "PAM30"))
system.time(statSignf(seq1, seq2, num.shuffles = 5000, shuffle.seq = 2))
system.time(statSignf(seq1, seq2, num.shuffles = 5000, kind.align = "local"))
