---
title: "Análisis de secuencias: `r params$name_fasta`"
author: "Alex-Alex-Helena"
date: '`r format(Sys.Date(),"%e %B, %Y")`'
output: 
  html_document:
    toc: false
  pdf_document: 
    toc: false
    latex_engine: xelatex
params:
  path: "/home/ajo/gitRepos/bioinformatics/Task2/fastas"
  name_fasta: "ENSG00000114374.fa"
  showCode: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "#>", warning = F, echo = params$showCode)

# Installs packages that have not been installed on the system automatically. 
# https://stackoverflow.com/questions/9341635/check-for-installed-packages-before-running-install-packages
packages <- c("Biostrings")
install.packages(setdiff(packages, rownames(installed.packages())))  

# Import packages listed in the 'packages' variable above. 
# https://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
lapply(packages, require, character.only = TRUE)


# Create the directory for the report. 
# directory <- paste(substr(params$name_fasta, 1,nchar(params$name_fasta)-3),"report", sep = "_") 
# if (file.exists(directory)) {
#  cat("The directory ",directory," already exists.")
# } else {
#  dir.create(directory)
#  cat("The directory ",directory," has been created..")
# }
```

```{r, echo = F, results = "hide"}
# the pdf engine cannot render this output because of the characters in the DNA table. Not sure if this can be fixed. 
filepath <- paste(params$path, params$name_fasta, sep = "/") # Should use file.path instead. 
DNA <- readDNAStringSet(filepath)
```

En este informe analizamos el fichero fasta (.fa) **`r params$name_fasta`**, que contiene exactamente `r length(DNA)`
registros y se encuentra en la carpeta "`r paste0("./", basename(params$path))`". A continuación resumo la tabla siguiente el número de
cuentas de Adenina, Guanina, Citosina y Timina de cada registro. También añado el número total de bases
nitrogenadas.

```{r}
count <- alphabetFrequency(DNA)[, c(1,2,3,4)]
#accession.number = strsplit(names(DNA), split = "|", fixed = T)
#names <- paste(accession.number[,1], accession.number[,2], sep = "|")
# Tried to select only the two first names (separated by pipes), but could not get the dimensions to work in the df.
accession.number <- lapply(names(DNA), substr, 1, 30) # Quick fix (only select the first 30 letters). At least it works with the example given. 
df <- cbind(Accession.number = accession.number, count, Total = rowSums(count)) # Use width(DNA) instead, since it solves problems when only one row also!
knitr::kable(df, caption = "Contaje de las bases nitrogenadas de cada registro")
```
